modifiying qtcreator project file to configure linker phase   * find opencv dependencies on *my* mac.   * mileage on your mac may be different. for instance i have a stale homebrew installation, and i needed to follow steps      * here (https://stackoverflow.com/questions/17643509/conflict- between-dynamic-linking-priority-in-osx) to unlink libjpeg and its friends to get around this         * (dyld: Symbol not found: __cg_jpeg_resync_to_restart  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO  Expected in: /opt/local/lib/libJPEG.dylib in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO Trace/BPT trap: 5) kind of error